name: Detik Scraper

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour
  workflow_dispatch:

jobs:
  scrape-and-upload:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Updated to v4
    
    - name: Set up Python
      uses: actions/setup-python@v5  # Updated to v5
      with:
        python-version: '3.10'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 yt-dlp
        
    - name: Create config files
      run: |
        mkdir -p downloaded_videos
        echo '${{ secrets.FACEBOOK_PAGES_JSON }}' > facebook_pages.json
        
    - name: Run scraper
      run: python 20detik.py
      
    - name: Upload logs as artifact
      if: always()
      uses: actions/upload-artifact@v4  # Updated to v4
      with:
        name: scraper-logs
        path: |
          posted_videos.json
          downloaded_videos/
        retention-days: 1  # Only keep artifacts for 1 day to save space
