name: Run Detik Scraper and Uploader

on:
  schedule:
    - cron: '0 */1 * * *'  # Jalankan setiap 4 jam
  workflow_dispatch:  # Izinkan trigger manual

jobs:
  scrape-and-upload:
    runs-on: ubuntu-latest

    steps:
      # Checkout kode dari repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # Instal FFmpeg
      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      # Instal dependensi Python
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Simpan facebook_pages.json dari secret
      - name: Create facebook_pages.json
        env:
          FB_PAGES_JSON: ${{ secrets.FACEBOOK_PAGES_JSON }}
        run: echo "$FB_PAGES_JSON" > facebook_pages.json

      # Jalankan skrip
      - name: Run Scraper and Uploader
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python main.py

      # Commit dan push posted_videos.json (jika ada perubahan)
      - name: Commit Updated posted_videos.json
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add posted_videos.json
          git diff --quiet && git diff --staged --quiet || git commit -m 'Update posted_videos.json'
          git push
        continue-on-error: true
